/*
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference
 *
 * Easy (51.54%)
 * Total Accepted:    69732
 * Total Submissions: 135292
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        int count[26];
        memset(count, 0, 26 * sizeof(int));
        
        for(auto c : t) { count[c-'a']++; }
        for(auto c : s) { count[c-'a']--; }
        for(int i=0;i<26;i++) { if(count[i]) return 'a' + i; }
    }
};
